  version: 0.2
  phases:
    install:
      runtime-versions:
        docker: 20
    pre_build:
      commands:
        - echo Logging in to Amazon ECR Public...
        - aws --version
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
        - aws --version
        - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
        - REPOSITORY_URI=public.ecr.aws/kousenko/hello
#        - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

    build:
      commands:
        - make all # build arm64 and amd64
        - for i in amd64 arm64; do docker tag hello:${i} ${REPOSITORY_URI}:${i}; done

    post_build:
      commands:
        - for i in amd64 arm64; do docker push ${REPOSITORY_URI}:${i}; done
#        - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

#artifacts:
#    files: imageDetail.json
